//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DiemSoap", Namespace="http://tempuri.org/")]
    public partial class Diem : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadDataDiemOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSinhVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMonHocOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDiemOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSinhVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMonHocOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDiemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteLopOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSinhVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMonHocOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDiemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Diem() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_localhost_Diem;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadDataDiemCompletedEventHandler ReadDataDiemCompleted;
        
        /// <remarks/>
        public event CreateLopCompletedEventHandler CreateLopCompleted;
        
        /// <remarks/>
        public event CreateSinhVienCompletedEventHandler CreateSinhVienCompleted;
        
        /// <remarks/>
        public event CreateMonHocCompletedEventHandler CreateMonHocCompleted;
        
        /// <remarks/>
        public event CreateDiemCompletedEventHandler CreateDiemCompleted;
        
        /// <remarks/>
        public event UpdateLopCompletedEventHandler UpdateLopCompleted;
        
        /// <remarks/>
        public event UpdateSinhVienCompletedEventHandler UpdateSinhVienCompleted;
        
        /// <remarks/>
        public event UpdateMonHocCompletedEventHandler UpdateMonHocCompleted;
        
        /// <remarks/>
        public event UpdateDiemCompletedEventHandler UpdateDiemCompleted;
        
        /// <remarks/>
        public event DeleteLopCompletedEventHandler DeleteLopCompleted;
        
        /// <remarks/>
        public event DeleteSinhVienCompletedEventHandler DeleteSinhVienCompleted;
        
        /// <remarks/>
        public event DeleteMonHocCompletedEventHandler DeleteMonHocCompleted;
        
        /// <remarks/>
        public event DeleteDiemCompletedEventHandler DeleteDiemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadDataDiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadDataDiem(string tableName, string id) {
            object[] results = this.Invoke("ReadDataDiem", new object[] {
                        tableName,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadDataDiemAsync(string tableName, string id) {
            this.ReadDataDiemAsync(tableName, id, null);
        }
        
        /// <remarks/>
        public void ReadDataDiemAsync(string tableName, string id, object userState) {
            if ((this.ReadDataDiemOperationCompleted == null)) {
                this.ReadDataDiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadDataDiemOperationCompleted);
            }
            this.InvokeAsync("ReadDataDiem", new object[] {
                        tableName,
                        id}, this.ReadDataDiemOperationCompleted, userState);
        }
        
        private void OnReadDataDiemOperationCompleted(object arg) {
            if ((this.ReadDataDiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadDataDiemCompleted(this, new ReadDataDiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateLop(string MaLop, string TenLop) {
            object[] results = this.Invoke("CreateLop", new object[] {
                        MaLop,
                        TenLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateLopAsync(string MaLop, string TenLop) {
            this.CreateLopAsync(MaLop, TenLop, null);
        }
        
        /// <remarks/>
        public void CreateLopAsync(string MaLop, string TenLop, object userState) {
            if ((this.CreateLopOperationCompleted == null)) {
                this.CreateLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateLopOperationCompleted);
            }
            this.InvokeAsync("CreateLop", new object[] {
                        MaLop,
                        TenLop}, this.CreateLopOperationCompleted, userState);
        }
        
        private void OnCreateLopOperationCompleted(object arg) {
            if ((this.CreateLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateLopCompleted(this, new CreateLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateSinhVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateSinhVien(string MaSV, string HoTen, System.DateTime NgaySinh, int GioiTinh, string DiaChi, string SoDT, string MaLop) {
            object[] results = this.Invoke("CreateSinhVien", new object[] {
                        MaSV,
                        HoTen,
                        NgaySinh,
                        GioiTinh,
                        DiaChi,
                        SoDT,
                        MaLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSinhVienAsync(string MaSV, string HoTen, System.DateTime NgaySinh, int GioiTinh, string DiaChi, string SoDT, string MaLop) {
            this.CreateSinhVienAsync(MaSV, HoTen, NgaySinh, GioiTinh, DiaChi, SoDT, MaLop, null);
        }
        
        /// <remarks/>
        public void CreateSinhVienAsync(string MaSV, string HoTen, System.DateTime NgaySinh, int GioiTinh, string DiaChi, string SoDT, string MaLop, object userState) {
            if ((this.CreateSinhVienOperationCompleted == null)) {
                this.CreateSinhVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSinhVienOperationCompleted);
            }
            this.InvokeAsync("CreateSinhVien", new object[] {
                        MaSV,
                        HoTen,
                        NgaySinh,
                        GioiTinh,
                        DiaChi,
                        SoDT,
                        MaLop}, this.CreateSinhVienOperationCompleted, userState);
        }
        
        private void OnCreateSinhVienOperationCompleted(object arg) {
            if ((this.CreateSinhVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSinhVienCompleted(this, new CreateSinhVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateMonHoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateMonHoc(string MaMH, string TenMH, int SoTiet, string TenGV, string HocKy, string MaLop) {
            object[] results = this.Invoke("CreateMonHoc", new object[] {
                        MaMH,
                        TenMH,
                        SoTiet,
                        TenGV,
                        HocKy,
                        MaLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateMonHocAsync(string MaMH, string TenMH, int SoTiet, string TenGV, string HocKy, string MaLop) {
            this.CreateMonHocAsync(MaMH, TenMH, SoTiet, TenGV, HocKy, MaLop, null);
        }
        
        /// <remarks/>
        public void CreateMonHocAsync(string MaMH, string TenMH, int SoTiet, string TenGV, string HocKy, string MaLop, object userState) {
            if ((this.CreateMonHocOperationCompleted == null)) {
                this.CreateMonHocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMonHocOperationCompleted);
            }
            this.InvokeAsync("CreateMonHoc", new object[] {
                        MaMH,
                        TenMH,
                        SoTiet,
                        TenGV,
                        HocKy,
                        MaLop}, this.CreateMonHocOperationCompleted, userState);
        }
        
        private void OnCreateMonHocOperationCompleted(object arg) {
            if ((this.CreateMonHocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMonHocCompleted(this, new CreateMonHocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateDiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateDiem(string MaSV, string MaMH, float Diem, string HocLuc) {
            object[] results = this.Invoke("CreateDiem", new object[] {
                        MaSV,
                        MaMH,
                        Diem,
                        HocLuc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDiemAsync(string MaSV, string MaMH, float Diem, string HocLuc) {
            this.CreateDiemAsync(MaSV, MaMH, Diem, HocLuc, null);
        }
        
        /// <remarks/>
        public void CreateDiemAsync(string MaSV, string MaMH, float Diem, string HocLuc, object userState) {
            if ((this.CreateDiemOperationCompleted == null)) {
                this.CreateDiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDiemOperationCompleted);
            }
            this.InvokeAsync("CreateDiem", new object[] {
                        MaSV,
                        MaMH,
                        Diem,
                        HocLuc}, this.CreateDiemOperationCompleted, userState);
        }
        
        private void OnCreateDiemOperationCompleted(object arg) {
            if ((this.CreateDiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDiemCompleted(this, new CreateDiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateLop(string MaLop, string TenLop) {
            object[] results = this.Invoke("UpdateLop", new object[] {
                        MaLop,
                        TenLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLopAsync(string MaLop, string TenLop) {
            this.UpdateLopAsync(MaLop, TenLop, null);
        }
        
        /// <remarks/>
        public void UpdateLopAsync(string MaLop, string TenLop, object userState) {
            if ((this.UpdateLopOperationCompleted == null)) {
                this.UpdateLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLopOperationCompleted);
            }
            this.InvokeAsync("UpdateLop", new object[] {
                        MaLop,
                        TenLop}, this.UpdateLopOperationCompleted, userState);
        }
        
        private void OnUpdateLopOperationCompleted(object arg) {
            if ((this.UpdateLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLopCompleted(this, new UpdateLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSinhVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateSinhVien(string MaSV, string HoTen, System.DateTime NgaySinh, int GioiTinh, string DiaChi, string SoDT, string MaLop) {
            object[] results = this.Invoke("UpdateSinhVien", new object[] {
                        MaSV,
                        HoTen,
                        NgaySinh,
                        GioiTinh,
                        DiaChi,
                        SoDT,
                        MaLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSinhVienAsync(string MaSV, string HoTen, System.DateTime NgaySinh, int GioiTinh, string DiaChi, string SoDT, string MaLop) {
            this.UpdateSinhVienAsync(MaSV, HoTen, NgaySinh, GioiTinh, DiaChi, SoDT, MaLop, null);
        }
        
        /// <remarks/>
        public void UpdateSinhVienAsync(string MaSV, string HoTen, System.DateTime NgaySinh, int GioiTinh, string DiaChi, string SoDT, string MaLop, object userState) {
            if ((this.UpdateSinhVienOperationCompleted == null)) {
                this.UpdateSinhVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSinhVienOperationCompleted);
            }
            this.InvokeAsync("UpdateSinhVien", new object[] {
                        MaSV,
                        HoTen,
                        NgaySinh,
                        GioiTinh,
                        DiaChi,
                        SoDT,
                        MaLop}, this.UpdateSinhVienOperationCompleted, userState);
        }
        
        private void OnUpdateSinhVienOperationCompleted(object arg) {
            if ((this.UpdateSinhVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSinhVienCompleted(this, new UpdateSinhVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMonHoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMonHoc(string MaMH, string TenMH, int SoTiet, string TenGV, string HocKy, string MaLop) {
            object[] results = this.Invoke("UpdateMonHoc", new object[] {
                        MaMH,
                        TenMH,
                        SoTiet,
                        TenGV,
                        HocKy,
                        MaLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMonHocAsync(string MaMH, string TenMH, int SoTiet, string TenGV, string HocKy, string MaLop) {
            this.UpdateMonHocAsync(MaMH, TenMH, SoTiet, TenGV, HocKy, MaLop, null);
        }
        
        /// <remarks/>
        public void UpdateMonHocAsync(string MaMH, string TenMH, int SoTiet, string TenGV, string HocKy, string MaLop, object userState) {
            if ((this.UpdateMonHocOperationCompleted == null)) {
                this.UpdateMonHocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMonHocOperationCompleted);
            }
            this.InvokeAsync("UpdateMonHoc", new object[] {
                        MaMH,
                        TenMH,
                        SoTiet,
                        TenGV,
                        HocKy,
                        MaLop}, this.UpdateMonHocOperationCompleted, userState);
        }
        
        private void OnUpdateMonHocOperationCompleted(object arg) {
            if ((this.UpdateMonHocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMonHocCompleted(this, new UpdateMonHocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateDiem(string MaSV, string MaMH, float Diem, string HocLuc) {
            object[] results = this.Invoke("UpdateDiem", new object[] {
                        MaSV,
                        MaMH,
                        Diem,
                        HocLuc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDiemAsync(string MaSV, string MaMH, float Diem, string HocLuc) {
            this.UpdateDiemAsync(MaSV, MaMH, Diem, HocLuc, null);
        }
        
        /// <remarks/>
        public void UpdateDiemAsync(string MaSV, string MaMH, float Diem, string HocLuc, object userState) {
            if ((this.UpdateDiemOperationCompleted == null)) {
                this.UpdateDiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDiemOperationCompleted);
            }
            this.InvokeAsync("UpdateDiem", new object[] {
                        MaSV,
                        MaMH,
                        Diem,
                        HocLuc}, this.UpdateDiemOperationCompleted, userState);
        }
        
        private void OnUpdateDiemOperationCompleted(object arg) {
            if ((this.UpdateDiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDiemCompleted(this, new UpdateDiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteLop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteLop(string MaLop) {
            object[] results = this.Invoke("DeleteLop", new object[] {
                        MaLop});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteLopAsync(string MaLop) {
            this.DeleteLopAsync(MaLop, null);
        }
        
        /// <remarks/>
        public void DeleteLopAsync(string MaLop, object userState) {
            if ((this.DeleteLopOperationCompleted == null)) {
                this.DeleteLopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteLopOperationCompleted);
            }
            this.InvokeAsync("DeleteLop", new object[] {
                        MaLop}, this.DeleteLopOperationCompleted, userState);
        }
        
        private void OnDeleteLopOperationCompleted(object arg) {
            if ((this.DeleteLopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteLopCompleted(this, new DeleteLopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteSinhVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteSinhVien(string MaSV) {
            object[] results = this.Invoke("DeleteSinhVien", new object[] {
                        MaSV});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSinhVienAsync(string MaSV) {
            this.DeleteSinhVienAsync(MaSV, null);
        }
        
        /// <remarks/>
        public void DeleteSinhVienAsync(string MaSV, object userState) {
            if ((this.DeleteSinhVienOperationCompleted == null)) {
                this.DeleteSinhVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSinhVienOperationCompleted);
            }
            this.InvokeAsync("DeleteSinhVien", new object[] {
                        MaSV}, this.DeleteSinhVienOperationCompleted, userState);
        }
        
        private void OnDeleteSinhVienOperationCompleted(object arg) {
            if ((this.DeleteSinhVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSinhVienCompleted(this, new DeleteSinhVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMonHoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteMonHoc(string MaMH) {
            object[] results = this.Invoke("DeleteMonHoc", new object[] {
                        MaMH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMonHocAsync(string MaMH) {
            this.DeleteMonHocAsync(MaMH, null);
        }
        
        /// <remarks/>
        public void DeleteMonHocAsync(string MaMH, object userState) {
            if ((this.DeleteMonHocOperationCompleted == null)) {
                this.DeleteMonHocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMonHocOperationCompleted);
            }
            this.InvokeAsync("DeleteMonHoc", new object[] {
                        MaMH}, this.DeleteMonHocOperationCompleted, userState);
        }
        
        private void OnDeleteMonHocOperationCompleted(object arg) {
            if ((this.DeleteMonHocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMonHocCompleted(this, new DeleteMonHocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteDiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteDiem(string MaSV, string MaMH) {
            object[] results = this.Invoke("DeleteDiem", new object[] {
                        MaSV,
                        MaMH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDiemAsync(string MaSV, string MaMH) {
            this.DeleteDiemAsync(MaSV, MaMH, null);
        }
        
        /// <remarks/>
        public void DeleteDiemAsync(string MaSV, string MaMH, object userState) {
            if ((this.DeleteDiemOperationCompleted == null)) {
                this.DeleteDiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDiemOperationCompleted);
            }
            this.InvokeAsync("DeleteDiem", new object[] {
                        MaSV,
                        MaMH}, this.DeleteDiemOperationCompleted, userState);
        }
        
        private void OnDeleteDiemOperationCompleted(object arg) {
            if ((this.DeleteDiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDiemCompleted(this, new DeleteDiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadDataDiemCompletedEventHandler(object sender, ReadDataDiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadDataDiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadDataDiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateLopCompletedEventHandler(object sender, CreateLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateSinhVienCompletedEventHandler(object sender, CreateSinhVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSinhVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSinhVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateMonHocCompletedEventHandler(object sender, CreateMonHocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMonHocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMonHocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateDiemCompletedEventHandler(object sender, CreateDiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateLopCompletedEventHandler(object sender, UpdateLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateSinhVienCompletedEventHandler(object sender, UpdateSinhVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSinhVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSinhVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateMonHocCompletedEventHandler(object sender, UpdateMonHocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMonHocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMonHocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateDiemCompletedEventHandler(object sender, UpdateDiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteLopCompletedEventHandler(object sender, DeleteLopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteLopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteLopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteSinhVienCompletedEventHandler(object sender, DeleteSinhVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSinhVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSinhVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteMonHocCompletedEventHandler(object sender, DeleteMonHocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMonHocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMonHocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteDiemCompletedEventHandler(object sender, DeleteDiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591